source "https://rubygems.org"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 8.1.3", ">= 8.1.3.1"
# Use PostgreSQL as the database for Active Record
gem "pg", "~> 1.5"
# Use the Puma web server [https://github.com/puma/puma]
gem "puma", ">= 5.0"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[windows jruby]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

gem "rack-cors"
gem "jwt"
gem "googleauth"
gem "ice_cube"
gem "rack-attack"

group :development, :test do
  gem "rubocop-rails-omakase", require: false
  gem "rspec-rails"
end

group :development do
  gem "bundler-audit", require: false
end
