// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: events.sql

package db

import (
	"context"
	"time"
)

const deleteEvent = `-- name: DeleteEvent :execrows
DELETE FROM events WHERE id = $1 AND user_id = $2
`

type DeleteEventParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteEvent(ctx context.Context, arg DeleteEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEvent, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findEventByIDAndUserID = `-- name: FindEventByIDAndUserID :one
SELECT id, user_id, title, description, start_at, end_at, all_day, recurrence_rule, created_at, updated_at
FROM events
WHERE id = $1 AND user_id = $2
`

type FindEventByIDAndUserIDParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) FindEventByIDAndUserID(ctx context.Context, arg FindEventByIDAndUserIDParams) (Event, error) {
	row := q.db.QueryRow(ctx, findEventByIDAndUserID, arg.ID, arg.UserID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.StartAt,
		&i.EndAt,
		&i.AllDay,
		&i.RecurrenceRule,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findEventCandidates = `-- name: FindEventCandidates :many
SELECT id, user_id, title, description, start_at, end_at, all_day, recurrence_rule, created_at, updated_at
FROM events
WHERE user_id = $1
  AND (
    (recurrence_rule IS NULL AND start_at <= $2 AND end_at >= $3)
    OR (recurrence_rule IS NOT NULL AND start_at <= $2)
  )
`

type FindEventCandidatesParams struct {
	UserID     int64
	ToBoundary time.Time
	RangeFrom  time.Time
}

func (q *Queries) FindEventCandidates(ctx context.Context, arg FindEventCandidatesParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, findEventCandidates, arg.UserID, arg.ToBoundary, arg.RangeFrom)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.StartAt,
			&i.EndAt,
			&i.AllDay,
			&i.RecurrenceRule,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertEvent = `-- name: InsertEvent :one
INSERT INTO events (user_id, title, description, start_at, end_at, all_day, recurrence_rule, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, title, description, start_at, end_at, all_day, recurrence_rule, created_at, updated_at
`

type InsertEventParams struct {
	UserID         int64
	Title          string
	Description    *string
	StartAt        time.Time
	EndAt          time.Time
	AllDay         bool
	RecurrenceRule *string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, insertEvent,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.StartAt,
		arg.EndAt,
		arg.AllDay,
		arg.RecurrenceRule,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.StartAt,
		&i.EndAt,
		&i.AllDay,
		&i.RecurrenceRule,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events
SET title = $3,
    description = $4,
    start_at = $5,
    end_at = $6,
    all_day = $7,
    recurrence_rule = $8,
    updated_at = $9
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, title, description, start_at, end_at, all_day, recurrence_rule, created_at, updated_at
`

type UpdateEventParams struct {
	ID             int64
	UserID         int64
	Title          string
	Description    *string
	StartAt        time.Time
	EndAt          time.Time
	AllDay         bool
	RecurrenceRule *string
	UpdatedAt      time.Time
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.StartAt,
		arg.EndAt,
		arg.AllDay,
		arg.RecurrenceRule,
		arg.UpdatedAt,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.StartAt,
		&i.EndAt,
		&i.AllDay,
		&i.RecurrenceRule,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
