// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"
)

type Event struct {
	ID              int64
	UserID          int64
	Title           string
	Description     *string
	StartAt         *time.Time
	EndAt           *time.Time
	AllDay          bool
	RecurrenceRule  *string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	StartOn         *time.Time
	EndOn           *time.Time
	ReminderMinutes *int32
}

type RefreshToken struct {
	ID          int64
	UserID      int64
	TokenDigest string
	ExpiresAt   time.Time
	RevokedAt   *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type ReminderDelivery struct {
	ID                int64
	UserID            int64
	EventID           int64
	OccurrenceStartAt time.Time
	DeliveredAt       *time.Time
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type User struct {
	ID        int64
	Email     string
	GoogleUid string
	Name      string
	AvatarUrl *string
	CreatedAt time.Time
	UpdatedAt time.Time
	TimeZone  string
}
