// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: refresh_tokens.sql

package db

import (
	"context"
	"time"
)

const claimIfActive = `-- name: ClaimIfActive :execrows
UPDATE refresh_tokens
SET revoked_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) ClaimIfActive(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, claimIfActive, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findRefreshTokenByDigest = `-- name: FindRefreshTokenByDigest :one
SELECT id, user_id, token_digest, expires_at, revoked_at, created_at, updated_at
FROM refresh_tokens
WHERE token_digest = $1
`

func (q *Queries) FindRefreshTokenByDigest(ctx context.Context, tokenDigest string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, findRefreshTokenByDigest, tokenDigest)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenDigest,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRefreshToken = `-- name: InsertRefreshToken :one
INSERT INTO refresh_tokens (user_id, token_digest, expires_at, revoked_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, token_digest, expires_at, revoked_at, created_at, updated_at
`

type InsertRefreshTokenParams struct {
	UserID      int64
	TokenDigest string
	ExpiresAt   time.Time
	RevokedAt   *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, insertRefreshToken,
		arg.UserID,
		arg.TokenDigest,
		arg.ExpiresAt,
		arg.RevokedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenDigest,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeAllActiveByUserID = `-- name: RevokeAllActiveByUserID :exec
UPDATE refresh_tokens
SET revoked_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllActiveByUserID(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, revokeAllActiveByUserID, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens
SET revoked_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, id)
	return err
}
