// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: reminders.sql

package db

import (
	"context"
	"time"
)

const findReminderDelivery = `-- name: FindReminderDelivery :one
SELECT id, user_id, event_id, occurrence_start_at, delivered_at, created_at, updated_at
FROM reminder_deliveries
WHERE event_id = $1 AND occurrence_start_at = $2
`

type FindReminderDeliveryParams struct {
	EventID           int64
	OccurrenceStartAt time.Time
}

func (q *Queries) FindReminderDelivery(ctx context.Context, arg FindReminderDeliveryParams) (ReminderDelivery, error) {
	row := q.db.QueryRow(ctx, findReminderDelivery, arg.EventID, arg.OccurrenceStartAt)
	var i ReminderDelivery
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.OccurrenceStartAt,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertReminderDelivery = `-- name: InsertReminderDelivery :execrows
INSERT INTO reminder_deliveries (user_id, event_id, occurrence_start_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (event_id, occurrence_start_at) DO NOTHING
`

type InsertReminderDeliveryParams struct {
	UserID            int64
	EventID           int64
	OccurrenceStartAt time.Time
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

func (q *Queries) InsertReminderDelivery(ctx context.Context, arg InsertReminderDeliveryParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertReminderDelivery,
		arg.UserID,
		arg.EventID,
		arg.OccurrenceStartAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markReminderDelivered = `-- name: MarkReminderDelivered :exec
UPDATE reminder_deliveries
SET delivered_at = $2,
    updated_at = $2
WHERE id = $1 AND delivered_at IS NULL
`

type MarkReminderDeliveredParams struct {
	ID          int64
	DeliveredAt *time.Time
}

func (q *Queries) MarkReminderDelivered(ctx context.Context, arg MarkReminderDeliveredParams) error {
	_, err := q.db.Exec(ctx, markReminderDelivered, arg.ID, arg.DeliveredAt)
	return err
}
