// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package db

import (
	"context"
	"time"
)

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id, email, google_uid, name, avatar_url, created_at, updated_at, time_zone
FROM users
WHERE email = $1
`

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.GoogleUid,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TimeZone,
	)
	return i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT id, email, google_uid, name, avatar_url, created_at, updated_at, time_zone
FROM users
WHERE id = $1
`

func (q *Queries) FindUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, findUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.GoogleUid,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TimeZone,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (email, google_uid, name, avatar_url, time_zone, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, email, google_uid, name, avatar_url, created_at, updated_at, time_zone
`

type InsertUserParams struct {
	Email     string
	GoogleUid string
	Name      string
	AvatarUrl *string
	TimeZone  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.Email,
		arg.GoogleUid,
		arg.Name,
		arg.AvatarUrl,
		arg.TimeZone,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.GoogleUid,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TimeZone,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET email = $2,
    google_uid = $3,
    name = $4,
    avatar_url = $5,
    time_zone = $6,
    updated_at = $7
WHERE id = $1
RETURNING id, email, google_uid, name, avatar_url, created_at, updated_at, time_zone
`

type UpdateUserParams struct {
	ID        int64
	Email     string
	GoogleUid string
	Name      string
	AvatarUrl *string
	TimeZone  string
	UpdatedAt time.Time
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.GoogleUid,
		arg.Name,
		arg.AvatarUrl,
		arg.TimeZone,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.GoogleUid,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TimeZone,
	)
	return i, err
}
